### ISSUE TITLE
GET requests for Home Page

### ISSUE THREAD

**Issue by aarav27** [joieng1/price-plate#28]
Estimate Time: 2-3 hours
On the home page
- Get all recipes from the database for that specific user (GET Request) and display on that home page
- When user clicks on recipe page, link to that specific recipe card
- Specific recipe card should link to the recipe that user created beforehand (GET Request)

**Comment by aarav27** [comment]
How is this task going?

**Comment by justinch4n** [comment]
Meant to close this issue. John got to it before me but just finished the Merge with frontend

**Comment by aarav27** [comment]
> Meant to close this issue. John got to it before me but just finished the Merge with frontend

Sounds good
