### ISSUE TITLE
Create Login Page

### ISSUE THREAD

**Issue by SilverXer0** [joieng1/price-plate#3]
- Make our login page as shown by our figma prototype
- Estimated Time: 2 Hours

**Comment by kailaaquino** [comment]
Just need to add logo 
Time: 1 hour 
<img width="759" alt="Screenshot 2024-05-20 at 8 48 37 PM" src="https://github.com/joieng1/price-plate/assets/94084013/8ed30de5-47c7-4b97-97fd-4d04eefc220f">

**Comment by SilverXer0** [comment]
Actual Time: 1 Hour
