### ISSUE TITLE
POST Request for Create Ingredient Page

### ISSUE THREAD

**Issue by SilverXer0** [joieng1/price-plate#35]
Create a Post request for the Create Ingredient Page so that pressing the Create Ingredient button creates an ingredient and takes you back to the main ingredient page. 

Estimated Time: 4 Hours

**Comment by kailaaquino** [comment]
note for my later commit: the login button is not redirecting so im gonna add that for my pull request for this issue

**Comment by SilverXer0** [comment]
Actual Time: 6 Hours
