### ISSUE TITLE
Create Sign up Page

### ISSUE THREAD

**Issue by SilverXer0** [joieng1/price-plate#4]
- Make our sign up page as shown by our Figma prototype
- Estimated Time: 3 Hours

**Comment by kailaaquino** [comment]
Just need to add logo 
Time: 3 hours
<img width="795" alt="Screenshot 2024-05-20 at 8 47 21 PM" src="https://github.com/joieng1/price-plate/assets/94084013/467af400-65c5-4992-8bb8-4717fd88b931">

**Comment by SilverXer0** [comment]
Actual Time: 3 Hours
