### ISSUE TITLE
Create Ingredient Card

### ISSUE THREAD

**Issue by joieng1** [joieng1/price-plate#5]
Based on the Figma UI, create the frontend component of the ingredients card with the respective fields. Note that this ingredients card should have an autofill (props for each field), and allow users to modify the ingredient.
Estimated Time: 3 Hours
<img width="929" alt="Screenshot 2024-05-09 at 3 15 49 PM" src="https://github.com/joieng1/price-plate/assets/70654142/3e5e5380-7424-46db-8f41-1f6f8900f80a">

**Comment by SilverXer0** [comment]
Actual Time: 4 Hours
