### ISSUE TITLE
Create Recipe Card

### ISSUE THREAD

**Issue by joieng1** [joieng1/price-plate#6]
Based on the Figma UI, create the frontend component for the recipe card. Note that this recipe card should have an autofill (props for each field), and allow users to modify the recipe.
Estimated Time: 5 Hours

<img width="707" alt="Screenshot 2024-05-09 at 3 17 12 PM" src="https://github.com/joieng1/price-plate/assets/70654142/d024ed29-8c0c-4904-9e31-3fcd715e4b75">

**Comment by SilverXer0** [comment]
Completed in Time: 2 Hours
