### ISSUE TITLE
Create "Create Ingredient Page"

### ISSUE THREAD

**Issue by joieng1** [joieng1/price-plate#7]
Based on the figma UI, create the frontend component for adding ingredients. 
Estimaed Time: 5 hours

<img width="444" alt="Screenshot 2024-05-09 at 3 21 02 PM" src="https://github.com/joieng1/price-plate/assets/70654142/c0e00347-2857-494c-9f8d-4f178dc5289f">

**Comment by SilverXer0** [comment]
Actual Time: 5 Hours
