### ISSUE TITLE
Fix nav bar routes - remove recipe from nav bar 

### ISSUE THREAD

**Issue by kailaaquino** [joieng1/price-plate#72]
Currently, the nav bar has a home and recipe page. In the prototype they lead to the same page. 
An option is to completely remove the recipe portion on the nav bar and just have the home page be the recipe page. 

Home -> add recipe -> create recipe card
Home -> view -> recipe card 

Files to fix: 
Navbar.tsx

Estimated time: 2 hours

**Comment by SilverXer0** [comment]
Actual Time: 3 Hours
